package com.iroid.patrickstore.model.single_product

data class SingleProduct(
    val __v: Int,
    val actualPrice: Any,
    val adminCommission: Int,
    val adminCommissionAmount: Double,
    val canSubtractStock: Boolean,
    val category: Category,
    val color: String,
    val costPrice: Int,
    val description: String,
    val discountDateFrom: String,
    val discountDateTo: String,
    val franchiseCommissionAmount: Double,
    val franchiseId: String,
    val height: String,
    val id: String,
    val imgUrl: List<ImgUrl>,
    val isApproved: Boolean,
    val isEnabled: Boolean,
    val isRejected: Boolean,
    val length: String,
    val maxDiscount: Int,
    val maxQuantity: Int,
    val minQunatity: Int,
    val model: String,
    val name: String,
    val offerPrice: Int,
    val productId: Int,
    val productTypeId: ProductTypeId,
    val quantity: Int,
    val reviews: List<Reviews>,
    val sellerId: SellerData,
    val shopAmount: Double,
    val shopDiscount: Int,
    val size: String,
    val tag: String,
    val weight: String,
    val width: String,
    val isWishListProduct:Boolean,
    val displayPrice:Double,


    )
