package com.property.propertyagent.modal.agent.agent_assigned_property_details

data class Property(
    val Bathroom: Int,
    val Beds: Int,
    val agent_details: AgentDetails ,
    val agent_id: Int ,
    val apartments: Int,
    val area: Int,
    val amenity_categories: List<AmenityCategory> ,
    val category: Int ,
    val city: String ,
    val city_rel: CityRel ,
    val country: String ,
    val country_rel: CountryRel ,
    val description: String ,
    val documents: List<Document> ,
    val expected_amount:String,
    val floor_plans: List<FloorPlan> ,
    val floors: Int ,
    val furnished: String ,
    val id: Int ,
    val is_featured: Int ,
    val is_builder: Int ,
    val latitude: String ,
    val longitude: String ,
    val mrp: String ,
    val occupied: String ,
    val owner_id: Int ,
    val owner_rel: OwnerRel ,
    val property_details: List<PropertyDetail> ,
    val property_name: String ,
    val property_reg_no: String ,
    val property_to: Int ,
    val property_type: String ,
    val rating: String ,
    val rent: String ,
    val selling_price: String ,
    val state: String ,
    val state_rel: StateRel ,
    val zip_code: Int ,
    val zipcode_rel: ZipcodeRel ,
    val street_address_1:String ,
    val street_address_2:String,
    val type_id : Int,
    val total_rating_count : Int
)