package com.property.propertyagent.utils

enum class EnumFromPage {
    PROFILE,
    MYPROFERTIES,
    MYEARNIBNGS,
    INHANDCASH,
    CHANGEPASSWORD,
    FEEDBACK,
    NOTIFICATION,
    QRREADER,
    MYTASKCALENDER,

    RESIDENTIAL_BUILDING,
    VILLA,
    APARTMENT,
    RESIDENTIAL_PLOT,
    COMMERCIAL_BUILDING,
    COMMERCIAL_PLOT,
    OFFICE,
    SHOP,
    WAREHOUSE,

    SERVICE,
    NOOFPROPERTY,
    OCCUPIEDPROPERTY,
    VACANTPROPERTY,
    UNDERMAINTANCE,


    SELECTEDTYPESID,
    SPINNERTYPE,
    SELECTEDPROPERTYTO,
    SELECTEDPROPERTYCATAGOREY,
    TEMPADDRESS1,
    TEMPADDRESS2,
    SELECTEDCOUNTRYID,
    SPINNERCOUNTRY,
    SELECTEDSTATEID,
    SPINNERSTATE,
    SELECTEDCITYID,
    SPINNERCITY,
    SELECTEDZIPCODEID,
    SPINNERZIPCODE
}